# Generated by Django 3.2.8 on 2021-10-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.TextField(max_length=200)),
                ('menu', models.CharField(max_length=200)),
                ('jenis', models.TextField(max_length=200)),
                ('nama', models.TextField(max_length=200)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='minuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.TextField(max_length=200)),
                ('jenis', models.TextField(max_length=200)),
                ('nama', models.TextField()),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pesanan_makanan', models.IntegerField()),
                ('jumlah_pesanan_minuman', models.IntegerField()),
                ('nama_makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.makanan')),
                ('nama_minuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.minuman')),
            ],
        ),
    ]
