# Generated by Django 3.2.8 on 2021-10-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='minuman',
            name='jumlah',
        ),
    ]
